// ============================================================
// languages.js - All translations for 3 languages
// Urdu (ur), English (en), Arabic (ar)
// ============================================================

const translations = {

  // ============================================================
  // URDU
  // ============================================================
  ur: {
    // Popup
    "popup.title": "زبان منتخب کریں",
    "popup.subtitle": "اپنی پسند کی زبان چنیں",
    "popup.later": "بعد میں",

    // Header
    "header.badge": "🌙 قرآن سیکھنے کا مرکز",
    "header.title": "قرآن پاک آن لائن تعلیم",
    "header.subtitle": "آسان، مفت، اور گھر بیٹھے قرآن کی تعلیم",
    "header.install": "ایپ انسٹال کریں",

    // Nav
    "nav.home": "ہوم",
    "nav.lessons": "سبق",
    "nav.bayan": "بیان",
    "nav.offline": "آف لائن",
    "nav.calendar": "کیلنڈر",
    "nav.progress": "پیش رفت",
    "nav.contact": "رابطہ",
    "nav.about": "تعارف",

    // Home
    "home.today": "آج کی اسلامی تاریخ",
    "home.welcome": "السلام علیکم ورحمۃ اللہ وبرکاتہ 🌙",
    "home.welcomeText": "یہ ایک مفت پلیٹ فارم ہے جہاں آپ گھر بیٹھے قرآن مجید سیکھ سکتے ہیں۔ ہمارا مقصد ہے کہ ہر بچہ آسان طریقے سے قرآن سے جڑ سکے۔",
    "home.todayTask": "آج کا کام",
    "home.todaySurah": "آج کی سورہ: سورہ الفاتحہ",
    "home.viewLessons": "📖 سبق دیکھیں",
    "home.viewBayan": "🎙️ بیان دیکھیں",
    "home.offlineBtn": "📥 آف لائن ڈاؤن لوڈ",
    "home.yourProgress": "آپ کی مجموعی پیش رفت",
    "home.noLesson": "ابھی تک کوئی سبق مکمل نہیں ہوا",
    "home.features": "ہماری خصوصیات",

    // Features
    "feature.quran": "مکمل قرآن",
    "feature.quranText": "تمام 114 سورتیں دستیاب",
    "feature.audio": "آڈیو تلاوت",
    "feature.audioText": "10 مشہور قاریوں کی آواز میں",
    "feature.bayan": "بیان",
    "feature.bayanText": "مولانا عبدالماجد ستی کی بیانات",
    "feature.tafsir": "اردو تفسیر",
    "feature.tafsirText": "ابن کثیر، فی ظلال، بیان القرآن",
    "feature.offline": "آف لائن موڈ",
    "feature.offlineText": "ایک بار ڈاؤن لوڈ، پھر بغیر انٹرنیٹ",

    // Stats
    "stats.totalSurahs": "کل سورتیں",
    "stats.completed": "مکمل شدہ",
    "stats.progress": "پیش رفت",

    // Lessons
    "lessons.selectSurah": "سورت منتخب کریں",
    "lessons.search": "🔍 سورت کا نام یا نمبر...",
    "lessons.noResults": "کوئی سورت نہیں ملی",
    "lessons.surahNum": "سورت نمبر",
    "lessons.totalAyahs": "کل آیات",
    "lessons.meccan": "مکی",
    "lessons.medinan": "مدنی",
    "lessons.ayah": "آیت",
    "lessons.viewTafsir": "📚 تفسیر دیکھیں",
    "lessons.closeTafsir": "📚 تفسیر بند کریں",
    "lessons.close": "✕ بند کریں",
    "lessons.iRead": "✅ میں نے پڑھ لی",
    "lessons.completed": "✅ مکمل ہو چکی ہے",
    "lessons.goTop": "⬆️ اوپر جائیں",
    "lessons.back": "← واپس",

    // Tafsir
    "tafsir.select": "📚 تفسیر منتخب کریں:",
    "tafsir.loading": "تفسیر لوڈ ہو رہی ہے...",
    "tafsir.notFound": "⚠️ اس آیت کی تفسیر دستیاب نہیں",
    "tafsir.ibnKathir": "ابن کثیر (اردو)",
    "tafsir.fiZilal": "فی ظلال القرآن (سید قطب)",
    "tafsir.bayan": "بیان القرآن (ڈاکٹر اسرار احمد)",

    // Audio
    "audio.recitation": "🎧 تلاوت",
    "audio.reciter": "قاری منتخب کریں",
    "audio.mishary": "مشاری العفاسی",
    "audio.abdulbasit": "عبدالباسط عبدالصمد",
    "audio.husary": "محمود خلیل الحصری",
    "audio.minshawi": "محمد صدیق منشاوی",
    "audio.hudhaify": "علی الحذیفی",
    "audio.shaatree": "ابو بکر الشاطری",
    "audio.ahmedajamy": "احمد بن علی العجمی",
    "audio.hanirifai": "ہانی الرفاعی",
    "audio.muhammadayyoub": "محمد ایوب",
    "audio.mahermuaiqly": "ماہر المعیقلی",
    "audio.notLoaded": "آڈیو لوڈ نہیں ہو سکی",
    "audio.offlineHint": "آف لائن — یہ آڈیو ابھی ڈاؤن لوڈ نہیں ہوئی۔ انٹرنیٹ سے جوڑیں۔",

    // Offline
    "offline.title": "آف لائن موڈ",
    "offline.text": "ایک بار یہاں سے ڈیٹا ڈاؤن لوڈ کریں، پھر یہ ایپ بغیر انٹرنیٹ بھی مکمل کام کرے گی۔",
    "offline.downloadTitle": "🌐 آف لائن ڈیٹا ڈاؤن لوڈ کریں",
    "offline.downloadText": "یہ ڈاؤن لوڈ کرنے سے پہلے انٹرنیٹ ضروری ہے۔ ڈاؤن لوڈ ہو جانے کے بعد آپ کو دوبارہ انٹرنیٹ کی ضرورت نہیں ہوگی۔",
    "offline.downloadNote": "نوٹ: پوری قرآن کی text download karne mein 2-5 minutes lag sakte hain.",
    "offline.downloadBtn": "تمام 114 سورتیں ڈاؤن لوڈ کریں",
    "offline.statusTitle": "📊 ڈاؤن لوڈ اسٹیٹس",
    "offline.cachedSurahs": "سورتیں:",
    "offline.cachedTafsir": "تفسیر:",
    "offline.cachedAudio": "آڈیو:",
    "offline.lastUpdate": "آخری اپ ڈیٹ:",
    "offline.never": "کبھی نہیں",
    "offline.clearCache": "🗑️ کیشے صاف کریں",
    "offline.downloading": "⏳ ڈاؤن لوڈ ہو رہا ہے...",
    "offline.done": "✅ ڈاؤن لوڈ مکمل",
    "offline.redownload": "🔄 دوبارہ ڈاؤن لوڈ کریں",
    "offline.completeMsg": "🎉 مکمل!",
    "offline.confirmClear": "کیا آپ تمام آف لائن ڈیٹا صاف کرنا چاہتے ہیں؟",
    "offline.cleared": "✅ تمام آف لائن ڈیٹا صاف کر دیا گیا",
    "offline.needInternet": "⚠️ آف لائن ڈاؤن لوڈ کے لیے انٹرنیٹ ضروری ہے۔",
    "offline.saved": "محفوظ ہو گئی",
    "offline.failed": "ڈاؤن لوڈ نہیں ہو سکی",
    "offline.alreadySaved": "پہلے سے محفوظ ہے",

    // Calendar
    "calendar.events": "2026 کے اہم اسلامی ایام",
    "calendar.convert": "تاریخ تبدیل کریں",
    "calendar.convertBtn": "🔄 تبدیل",
    "calendar.prayer": "نماز کے اوقات",
    "calendar.useMyLocation": "میری لوکیشن استعمال کریں",
    "calendar.selectCity": "شہر منتخب کریں",
    "calendar.currentLocation": "موجودہ:",
    "calendar.selectDate": "⚠️ پہلے تاریخ منتخب کریں",
    "calendar.converting": "🔄 تبدیل ہو رہی ہے...",
    "calendar.needInternet": "⚠️ تاریخ تبدیل کرنے کے لیے انٹرنیٹ ضروری ہے",
    "calendar.fajr": "فجر",
    "calendar.sunrise": "طلوعِ آفتاب",
    "calendar.dhuhr": "ظہر",
    "calendar.asr": "عصر",
    "calendar.maghrib": "مغرب",
    "calendar.isha": "عشاء",
    "calendar.locationDenied": "لوکیشن کی اجازت نہیں دی گئی",
    "calendar.locationError": "لوکیشن حاصل نہیں ہو سکی",
    "calendar.locationSet": "لوکیشن سیٹ ہو گئی",

    // Progress
    "progress.title": "اپنی پیش رفت درج کریں",
    "progress.formPlaceholder": "Google Form یہاں لگائیں",
    "progress.completed": "مکمل شدہ سبق",
    "progress.reset": "🔄 سب صاف کریں",
    "progress.none": "ابھی تک کوئی سورت مکمل نہیں ہوئی۔",
    "progress.resetConfirm": "کیا آپ واقعی ساری پیش رفت صاف کرنا چاہتے ہیں؟",
    "progress.marked": "ماشاء اللہ! سورت مکمل ہو گئی 🌟",
    "progress.alreadyDone": "یہ سورت پہلے ہی مکمل ہے ✅",

    // Contact
    "contact.title": "رابطہ کریں",
    "contact.role": "قرآن کے استاد — اسلام آباد",
    "contact.mobile": "موبائل نمبر",
    "contact.whatsapp": "واٹس ایپ",
    "contact.youtube": "یوٹیوب",
    "contact.time": "کلاس کا وقت",
    "contact.timeValue": "واٹس ایپ پر طے",
    "contact.whatsappBtn": "واٹس ایپ پر رابطہ کریں",
    "contact.bayanTitle": "بیان — مولانا عبدالماجد ستی",

    // About
    "about.title": "ہمارے بارے میں",
    "about.text1": "یہ ویب سائٹ زہیب ظہیر ستی کی کوشش ہے جو قرآن سیکھ رہے ہیں اور اپنے آس پاس کے بچوں کو بھی قرآن پڑھانا چاہتے ہیں۔",
    "about.text2": "یہ منصوبہ مکمل طور پر مفت ہے، اور اللہ کی رضا کے لیے ہے۔",
    "about.dua": "دعا",
    "about.duaText": "اللہ تعالیٰ ہمیں قرآن سیکھنے اور سکھانے کی توفیق دے۔ آمین",

    // Bayan
    "bayan.name": "مولانا عبدالماجد ستی",
    "bayan.role": "اسلامی عالم — اسلام آباد، پاکستان",
    "bayan.whatsapp": "واٹس ایپ",
    "bayan.youtube": "یوٹیوب",
    "bayan.call": "کال",
    "bayan.allVideos": "تمام بیانات",
    "bayan.tapToPlay": "ویڈیو چلانے کے لیے کارڈ پر کلک کریں",
    "bayan.prev": "پچھلی",
    "bayan.next": "اگلی",
    "bayan.watchOnYouTube": "یوٹیوب پر دیکھیں",
    "bayan.playHere": "یہیں چلائیں",

    // Footer
    "footer.dua": "اللہ ہمیں قرآن سیکھنے اور سکھانے کی توفیق دے۔ آمین 🤲",

    // Common
    "common.loading": "لوڈ ہو رہی ہے...",
    "common.surah": "سورہ",
    "common.error": "⚠️ معذرت، سورت لوڈ نہیں ہو سکی",
    "common.retry": "🔄 دوبارہ کوشش",
    "common.checkInternet": "براہ کرم انٹرنیٹ چیک کریں",
    "common.language": "زبان",
    "common.offline": "آف لائن",
    "common.online": "آن لائن",
    "common.today": "آج",
  },

  // ============================================================
  // ENGLISH
  // ============================================================
  en: {
    "popup.title": "Choose Your Language",
    "popup.subtitle": "Select your preferred language",
    "popup.later": "Later",

    "header.badge": "🌙 Quran Learning Center",
    "header.title": "Quran Online Teaching",
    "header.subtitle": "Easy, free, and learn Quran from home",
    "header.install": "Install App",

    "nav.home": "Home",
    "nav.lessons": "Lessons",
    "nav.bayan": "Bayan",
    "nav.offline": "Offline",
    "nav.calendar": "Calendar",
    "nav.progress": "Progress",
    "nav.contact": "Contact",
    "nav.about": "About",

    "home.today": "Today's Islamic Date",
    "home.welcome": "Assalamu Alaikum Wa Rahmatullah 🌙",
    "home.welcomeText": "This is a free platform where you can learn the Holy Quran from home. Our goal is that every child can easily connect with the Quran.",
    "home.todayTask": "Today's Task",
    "home.todaySurah": "Today's Surah: Surah Al-Fatihah",
    "home.viewLessons": "📖 View Lessons",
    "home.viewBayan": "🎙️ View Bayan",
    "home.offlineBtn": "📥 Offline Download",
    "home.yourProgress": "Your Overall Progress",
    "home.noLesson": "No lesson completed yet",
    "home.features": "Our Features",

    "feature.quran": "Complete Quran",
    "feature.quranText": "All 114 Surahs available",
    "feature.audio": "Audio Recitation",
    "feature.audioText": "In the voice of 10 famous reciters",
    "feature.bayan": "Bayan",
    "feature.bayanText": "Lectures by Maulana Abdul Majid Satti",
    "feature.tafsir": "Urdu Tafsir",
    "feature.tafsirText": "Ibn Kathir, Fi Zilal, Bayan ul Quran",
    "feature.offline": "Offline Mode",
    "feature.offlineText": "Download once, then no internet needed",

    "stats.totalSurahs": "Total Surahs",
    "stats.completed": "Completed",
    "stats.progress": "Progress",

    "lessons.selectSurah": "Select a Surah",
    "lessons.search": "🔍 Surah name or number...",
    "lessons.noResults": "No Surah found",
    "lessons.surahNum": "Surah Number",
    "lessons.totalAyahs": "Total Ayahs",
    "lessons.meccan": "Meccan",
    "lessons.medinan": "Medinan",
    "lessons.ayah": "Ayah",
    "lessons.viewTafsir": "📚 View Tafsir",
    "lessons.closeTafsir": "📚 Close Tafsir",
    "lessons.close": "✕ Close",
    "lessons.iRead": "✅ I Have Read",
    "lessons.completed": "✅ Completed",
    "lessons.goTop": "⬆️ Go to Top",
    "lessons.back": "← Back",

    "tafsir.select": "📚 Select Tafsir:",
    "tafsir.loading": "Loading Tafsir...",
    "tafsir.notFound": "⚠️ Tafsir not available for this Ayah",
    "tafsir.ibnKathir": "Ibn Kathir (English)",
    "tafsir.fiZilal": "In the Shade of the Quran",
    "tafsir.bayan": "Bayan ul Quran",

    "audio.recitation": "🎧 Recitation",
    "audio.reciter": "Select Reciter",
    "audio.mishary": "Mishary Al-Afasy",
    "audio.abdulbasit": "Abdul Basit Abdul Samad",
    "audio.husary": "Mahmoud Khalil Al-Husary",
    "audio.minshawi": "Muhammad Siddiq Al-Minshawi",
    "audio.hudhaify": "Ali Al-Hudhaify",
    "audio.shaatree": "Abu Bakr Ash-Shaatree",
    "audio.ahmedajamy": "Ahmed bin Ali Al-Ajamy",
    "audio.hanirifai": "Hani Ar-Rifai",
    "audio.muhammadayyoub": "Muhammad Ayyoub",
    "audio.mahermuaiqly": "Maher Al-Muaiqly",
    "audio.notLoaded": "Audio could not be loaded",
    "audio.offlineHint": "Offline — This audio is not downloaded yet. Connect to internet.",

    "offline.title": "Offline Mode",
    "offline.text": "Download data once from here, then this app will work fully without internet.",
    "offline.downloadTitle": "🌐 Download Offline Data",
    "offline.downloadText": "Internet is required before downloading. After download is complete, you won't need internet again.",
    "offline.downloadNote": "Note: Downloading the entire Quran text may take 2-5 minutes.",
    "offline.downloadBtn": "Download All 114 Surahs",
    "offline.statusTitle": "📊 Download Status",
    "offline.cachedSurahs": "Surahs:",
    "offline.cachedTafsir": "Tafsir:",
    "offline.cachedAudio": "Audio:",
    "offline.lastUpdate": "Last Update:",
    "offline.never": "Never",
    "offline.clearCache": "🗑️ Clear Cache",
    "offline.downloading": "⏳ Downloading...",
    "offline.done": "✅ Download Complete",
    "offline.redownload": "🔄 Re-download",
    "offline.completeMsg": "🎉 Complete!",
    "offline.confirmClear": "Do you want to clear all offline data?",
    "offline.cleared": "✅ All offline data cleared",
    "offline.needInternet": "⚠️ Internet is required for offline download.",
    "offline.saved": "saved",
    "offline.failed": "failed",
    "offline.alreadySaved": "already saved",

    "calendar.events": "Important Islamic Dates 2026",
    "calendar.convert": "Convert Date",
    "calendar.convertBtn": "🔄 Convert",
    "calendar.prayer": "Prayer Times",
    "calendar.useMyLocation": "Use My Location",
    "calendar.selectCity": "Select City",
    "calendar.currentLocation": "Current:",
    "calendar.selectDate": "⚠️ Please select a date first",
    "calendar.converting": "🔄 Converting...",
    "calendar.needInternet": "⚠️ Internet is required to convert date",
    "calendar.fajr": "Fajr",
    "calendar.sunrise": "Sunrise",
    "calendar.dhuhr": "Dhuhr",
    "calendar.asr": "Asr",
    "calendar.maghrib": "Maghrib",
    "calendar.isha": "Isha",
    "calendar.locationDenied": "Location permission denied",
    "calendar.locationError": "Could not get location",
    "calendar.locationSet": "Location set",

    "progress.title": "Record Your Progress",
    "progress.formPlaceholder": "Paste Google Form here",
    "progress.completed": "Completed Lessons",
    "progress.reset": "🔄 Clear All",
    "progress.none": "No Surah completed yet.",
    "progress.resetConfirm": "Do you really want to clear all progress?",
    "progress.marked": "MashaAllah! Surah completed 🌟",
    "progress.alreadyDone": "This Surah is already completed ✅",

    "contact.title": "Contact Us",
    "contact.role": "Quran Teacher — Islamabad",
    "contact.mobile": "Mobile Number",
    "contact.whatsapp": "WhatsApp",
    "contact.youtube": "YouTube",
    "contact.time": "Class Time",
    "contact.timeValue": "Set on WhatsApp",
    "contact.whatsappBtn": "Contact on WhatsApp",
    "contact.bayanTitle": "Bayan — Maulana Abdul Majid Satti",

    "about.title": "About Us",
    "about.text1": "This website is an effort by Zohaib Zaheer Satti who is learning Quran and wants to teach Quran to children around him.",
    "about.text2": "This project is completely free, and for the pleasure of Allah.",
    "about.dua": "Dua",
    "about.duaText": "May Allah give us the ability to learn and teach the Quran. Ameen",

    "bayan.name": "Maulana Abdul Majid Satti",
    "bayan.role": "Islamic Scholar — Islamabad, Pakistan",
    "bayan.whatsapp": "WhatsApp",
    "bayan.youtube": "YouTube",
    "bayan.call": "Call",
    "bayan.allVideos": "All Lectures",
    "bayan.tapToPlay": "Tap a card to play the video",
    "bayan.prev": "Previous",
    "bayan.next": "Next",
    "bayan.watchOnYouTube": "Watch on YouTube",
    "bayan.playHere": "Play Here",

    "footer.dua": "May Allah give us the ability to learn and teach the Quran. Ameen 🤲",

    "common.loading": "Loading...",
    "common.surah": "Surah",
    "common.error": "⚠️ Sorry, Surah could not be loaded",
    "common.retry": "🔄 Retry",
    "common.checkInternet": "Please check your internet",
    "common.language": "Language",
    "common.offline": "Offline",
    "common.online": "Online",
    "common.today": "Today",
  },

  // ============================================================
  // ARABIC
  // ============================================================
  ar: {
    "popup.title": "اختر اللغة",
    "popup.subtitle": "اختر لغتك المفضلة",
    "popup.later": "لاحقاً",

    "header.badge": "🌙 مركز تعلم القرآن",
    "header.title": "تعليم القرآن الكريم عبر الإنترنت",
    "header.subtitle": "سهل ومجاني وتعلم القرآن من المنزل",
    "header.install": "تثبيت التطبيق",

    "nav.home": "الرئيسية",
    "nav.lessons": "الدروس",
    "nav.bayan": "البيان",
    "nav.offline": "دون اتصال",
    "nav.calendar": "التقويم",
    "nav.progress": "التقدم",
    "nav.contact": "اتصل",
    "nav.about": "عن",

    "home.today": "التاريخ الإسلامي اليوم",
    "home.welcome": "السلام عليكم ورحمة الله 🌙",
    "home.welcomeText": "هذه منصة مجانية حيث يمكنك تعلم القرآن الكريم من المنزل. هدفنا أن يتصل كل طفل بالقرآن بسهولة.",
    "home.todayTask": "مهمة اليوم",
    "home.todaySurah": "سورة اليوم: سورة الفاتحة",
    "home.viewLessons": "📖 عرض الدروس",
    "home.viewBayan": "🎙️ عرض البيان",
    "home.offlineBtn": "📥 تحميل دون اتصال",
    "home.yourProgress": "تقدمك العام",
    "home.noLesson": "لم يكتمل أي درس بعد",
    "home.features": "ميزاتنا",

    "feature.quran": "القرآن كاملاً",
    "feature.quranText": "جميع السور الـ 114 متوفرة",
    "feature.audio": "التلاوة الصوتية",
    "feature.audioText": "بصوت 10 قراء مشهورين",
    "feature.bayan": "البيان",
    "feature.bayanText": "دروس مولانا عبد الماجد ستي",
    "feature.tafsir": "التفسير",
    "feature.tafsirText": "ابن كثير، في ظلال القرآن، بيان القرآن",
    "feature.offline": "وضع دون اتصال",
    "feature.offlineText": "حمّل مرة واحدة، ثم لا تحتاج للإنترنت",

    "stats.totalSurahs": "إجمالي السور",
    "stats.completed": "مكتمل",
    "stats.progress": "التقدم",

    "lessons.selectSurah": "اختر سورة",
    "lessons.search": "🔍 اسم السورة أو رقمها...",
    "lessons.noResults": "لم يتم العثور على سورة",
    "lessons.surahNum": "رقم السورة",
    "lessons.totalAyahs": "إجمالي الآيات",
    "lessons.meccan": "مكية",
    "lessons.medinan": "مدنية",
    "lessons.ayah": "آية",
    "lessons.viewTafsir": "📚 عرض التفسير",
    "lessons.closeTafsir": "📚 إغلاق التفسير",
    "lessons.close": "✕ إغلاق",
    "lessons.iRead": "✅ لقد قرأت",
    "lessons.completed": "✅ مكتمل",
    "lessons.goTop": "⬆️ أعلى الصفحة",
    "lessons.back": "← رجوع",

    "tafsir.select": "📚 اختر التفسير:",
    "tafsir.loading": "جاري تحميل التفسير...",
    "tafsir.notFound": "⚠️ التفسير غير متوفر لهذه الآية",
    "tafsir.ibnKathir": "ابن كثير (عربي)",
    "tafsir.fiZilal": "في ظلال القرآن",
    "tafsir.bayan": "بيان القرآن",

    "audio.recitation": "🎧 التلاوة",
    "audio.reciter": "اختر القارئ",
    "audio.mishary": "مشاري العفاسي",
    "audio.abdulbasit": "عبد الباسط عبد الصمد",
    "audio.husary": "محمود خليل الحصري",
    "audio.minshawi": "محمد صديق المنشاوي",
    "audio.hudhaify": "علي الحذيفي",
    "audio.shaatree": "أبو بكر الشاطري",
    "audio.ahmedajamy": "أحمد بن علي العجمي",
    "audio.hanirifai": "هاني الرفاعي",
    "audio.muhammadayyoub": "محمد أيوب",
    "audio.mahermuaiqly": "ماهر المعيقلي",
    "audio.notLoaded": "تعذر تحميل الصوت",
    "audio.offlineHint": "دون اتصال — هذا الصوت لم يتم تحميله بعد.",

    "offline.title": "وضع دون اتصال",
    "offline.text": "حمّل البيانات مرة واحدة من هنا، ثم سيعمل التطبيق بالكامل دون إنترنت.",
    "offline.downloadTitle": "🌐 تحميل بيانات دون اتصال",
    "offline.downloadText": "الإنترنت مطلوب قبل التحميل.",
    "offline.downloadNote": "ملاحظة: قد يستغرق تحميل نص القرآن بالكامل 2-5 دقائق.",
    "offline.downloadBtn": "تحميل جميع السور الـ 114",
    "offline.statusTitle": "📊 حالة التحميل",
    "offline.cachedSurahs": "السور:",
    "offline.cachedTafsir": "التفسير:",
    "offline.cachedAudio": "الصوت:",
    "offline.lastUpdate": "آخر تحديث:",
    "offline.never": "أبداً",
    "offline.clearCache": "🗑️ مسح الذاكرة",
    "offline.downloading": "⏳ جاري التحميل...",
    "offline.done": "✅ اكتمل التحميل",
    "offline.redownload": "🔄 إعادة التحميل",
    "offline.completeMsg": "🎉 اكتمل!",
    "offline.confirmClear": "هل تريد مسح جميع البيانات دون اتصال؟",
    "offline.cleared": "✅ تم مسح جميع البيانات",
    "offline.needInternet": "⚠️ الإنترنت مطلوب للتحميل دون اتصال.",
    "offline.saved": "تم الحفظ",
    "offline.failed": "فشل",
    "offline.alreadySaved": "محفوظ بالفعل",

    "calendar.events": "أهم التواريخ الإسلامية 2026",
    "calendar.convert": "تحويل التاريخ",
    "calendar.convertBtn": "🔄 تحويل",
    "calendar.prayer": "أوقات الصلاة",
    "calendar.useMyLocation": "استخدم موقعي",
    "calendar.selectCity": "اختر المدينة",
    "calendar.currentLocation": "الحالي:",
    "calendar.selectDate": "⚠️ الرجاء اختيار تاريخ أولاً",
    "calendar.converting": "🔄 جاري التحويل...",
    "calendar.needInternet": "⚠️ الإنترنت مطلوب لتحويل التاريخ",
    "calendar.fajr": "الفجر",
    "calendar.sunrise": "الشروق",
    "calendar.dhuhr": "الظهر",
    "calendar.asr": "العصر",
    "calendar.maghrib": "المغرب",
    "calendar.isha": "العشاء",
    "calendar.locationDenied": "تم رفض إذن الموقع",
    "calendar.locationError": "تعذر الحصول على الموقع",
    "calendar.locationSet": "تم تحديد الموقع",

    "progress.title": "سجل تقدمك",
    "progress.formPlaceholder": "الصق نموذج Google هنا",
    "progress.completed": "الدروس المكتملة",
    "progress.reset": "🔄 مسح الكل",
    "progress.none": "لم تكتمل أي سورة بعد.",
    "progress.resetConfirm": "هل تريد حقاً مسح كل التقدم؟",
    "progress.marked": "ما شاء الله! اكتملت السورة 🌟",
    "progress.alreadyDone": "هذه السورة مكتملة بالفعل ✅",

    "contact.title": "اتصل بنا",
    "contact.role": "معلم القرآن — إسلام آباد",
    "contact.mobile": "رقم الجوال",
    "contact.whatsapp": "واتساب",
    "contact.youtube": "يوتيوب",
    "contact.time": "وقت الحصة",
    "contact.timeValue": "يُحدد على واتساب",
    "contact.whatsappBtn": "تواصل على واتساب",
    "contact.bayanTitle": "البيان — مولانا عبد الماجد ستي",

    "about.title": "من نحن",
    "about.text1": "هذا الموقع جهد من زهيب ظهير ستي الذي يتعلم القرآن ويريد تعليم القرآن للأطفال من حوله.",
    "about.text2": "هذا المشروع مجاني تماماً، ولوجه الله تعالى.",
    "about.dua": "دعاء",
    "about.duaText": "اللهم اجعلنا من الذين يتعلمون ويعلمون القرآن. آمين",

    "bayan.name": "مولانا عبد الماجد ستي",
    "bayan.role": "عالم إسلامي — إسلام آباد، باكستان",
    "bayan.whatsapp": "واتساب",
    "bayan.youtube": "يوتيوب",
    "bayan.call": "اتصال",
    "bayan.allVideos": "جميع الدروس",
    "bayan.tapToPlay": "اضغط على البطاقة لتشغيل الفيديو",
    "bayan.prev": "السابق",
    "bayan.next": "التالي",
    "bayan.watchOnYouTube": "شاهد على يوتيوب",
    "bayan.playHere": "تشغيل هنا",

    "footer.dua": "اللهم اجعلنا من الذين يتعلمون ويعلمون القرآن. آمين 🤲",

    "common.loading": "جاري التحميل...",
    "common.surah": "سورة",
    "common.error": "⚠️ عذراً، لم يتم تحميل السورة",
    "common.retry": "🔄 إعادة المحاولة",
    "common.checkInternet": "يرجى التحقق من الإنترنت",
    "common.language": "اللغة",
    "common.offline": "دون اتصال",
    "common.online": "متصل",
    "common.today": "اليوم",
  }
};

// ============================================================
// Language metadata
// ============================================================
const languageMeta = {
  ur: { name: "اردو", english: "Urdu", dir: "rtl", flag: "🇵🇰" },
  en: { name: "English", english: "English", dir: "ltr", flag: "🇬🇧" },
  ar: { name: "العربية", english: "Arabic", dir: "rtl", flag: "🇸🇦" }
};

// ============================================================
// Helper: Get translation
// ============================================================
function t(key, lang) {
  const currentLang = lang || localStorage.getItem('appLang') || 'ur';
  if (translations[currentLang] && translations[currentLang][key]) {
    return translations[currentLang][key];
  }
  if (translations.ur[key]) return translations.ur[key];
  return key;
}